-- ============================================================================
--  ADVISÓRIO — NÃO é uma migration, NÃO está em supabase/migrations/
-- ============================================================================
--
--  Por quê este arquivo existe fora do fluxo normal de migrations
--
--  public.try_apply_coupon(...) e public.revert_coupon_usage(...) — as duas
--  RPCs que de fato aplicam/revertem o uso de um cupom de desconto de forma
--  atômica em app/api/checkout/route.ts — não têm `CREATE FUNCTION` em
--  nenhuma migration deste repositório. A migration
--  supabase/migrations/20260825150400_lock_down_coupons.sql documenta as
--  PERMISSÕES dessas duas funções (SECURITY DEFINER, EXECUTE restrito a
--  service_role) mas nunca o corpo real delas — foram criadas fora do
--  histórico de versionamento, mesma classe de risco já documentada para
--  public.is_admin() em ADVISORY_is_admin_baseline.sql.
--
--  Esta instância é mais sensível que a de is_admin(): aqui a função controla
--  se um cupom de desconto pode ser aplicado mais de uma vez além do
--  max_uses configurado — ou seja, integridade de receita, não só
--  autorização administrativa. Por isso este advisório NÃO tenta reconstruir
--  a lógica (ao contrário do ADVISORY_is_admin_baseline.sql, que reconstruiu
--  is_admin() com alta confiança a partir de evidência indireta forte): uma
--  reconstrução errada de "quando o cupom pode ser reaplicado" é pior que não
--  ter migration nenhuma — poderia introduzir silenciosamente uma janela de
--  corrida ou um bypass de max_uses que não existe hoje. Este projeto já teve
--  uma regressão real e documentada (migration 20260828130000) causada
--  exatamente por um `CREATE OR REPLACE FUNCTION` que não repetiu todas as
--  cláusulas de segurança da versão anterior.
--
--  COMO VERSIONAR ISSO COM SEGURANÇA
--
--  1. No SQL Editor de produção, rode:
--
--       select pg_get_functiondef('public.try_apply_coupon'::regprocedure);
--       select pg_get_functiondef('public.revert_coupon_usage'::regprocedure);
--
--     (Se houver mais de uma sobrecarga por nome, use
--      `select oid::regprocedure from pg_proc where proname in
--       ('try_apply_coupon','revert_coupon_usage')` primeiro para pegar a
--      assinatura exata de cada uma.)
--
--  2. Copie o resultado literal de cada uma — não reescreva, não resuma.
--
--  3. Cole as duas definições completas numa migration nova, com timestamp
--     válido, em supabase/migrations/, junto com um comentário explicando
--     que é uma migration de BASELINE (versiona o que já existe, não muda
--     comportamento).
--
--  4. Antes de aplicar em produção, revise manualmente a lógica de
--     atomicidade (ex.: se o UPDATE usa `WHERE usage_count < max_uses` na
--     mesma instrução, ou se há alguma janela entre leitura e escrita) — esta
--     auditoria não conseguiu confirmar isso a partir do comportamento
--     observado do chamador.
--
--  5. Teste em staging/preview antes de produção, se houver um.
-- ============================================================================
